/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2016-02-25 18:50:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.text.NumberFormat;
import java.util.Locale;
import java.text.DecimalFormat;
import java.util.ArrayList;
import fi.pizzeriaprojekti.admin.bean.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/Tyotilat/Pizzeria/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/PizzeriaProjekti/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153374282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1456425564713L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("fi.pizzeriaprojekti.admin.bean");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Locale");
    _jspx_imports_classes.add("java.text.DecimalFormat");
    _jspx_imports_classes.add("java.text.NumberFormat");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function readCookie(name){\r\n");
      out.write("return(document.cookie.match('(^|; )'+name+'=([^;]*)')||0)[2]\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<title>Ravintola - FIORI e CASTELLO</title>\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=320, height=device-height, target-densitydpi=medium-dpi\" />\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta content=\"width=device-width, initial-scale=1\" name=\"viewport\">\r\n");
      out.write("<!-- Bootstrap -->\r\n");
      out.write("<link href=\"css/bootstrap.min.css\" media=\"screen\" rel=\"stylesheet\">\r\n");
      out.write("<!-- Omat tyylit -->\r\n");
      out.write("<link href=\"css/default.css\" media=\"screen\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"css/default_max768.css\" media=\"screen and (max-width: 768px)\" rel=\"stylesheet\">\r\n");
      out.write("<!-- link href=\"css/scrolling-nav.css\" media=\"screen\" rel=\"stylesheet\" -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link href='https://fonts.googleapis.com/css?family=Josefin+Sans:600'\r\n");
      out.write("\trel='stylesheet' type='text/css'>\r\n");
      out.write("<link href='https://fonts.googleapis.com/css?family=Hammersmith+One'\r\n");
      out.write("\trel='stylesheet' type='text/css'>\r\n");
      out.write("<link href='https://fonts.googleapis.com/css?family=Capriola'\r\n");
      out.write("\trel='stylesheet' type='text/css'>\r\n");
      out.write("<link href='https://fonts.googleapis.com/css?family=Lobster'\r\n");
      out.write("\trel='stylesheet' type='text/css'>\t\r\n");
      out.write("\r\n");
      out.write("<link href='https://fonts.googleapis.com/css?family=Caveat'\r\n");
      out.write("\trel='stylesheet' type='text/css'>\r\n");
      out.write("<link href='https://fonts.googleapis.com/css?family=Quando'\r\n");
      out.write("\trel='stylesheet' type='text/css'>\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!--script src=\"scrollfix.js\" type=\"text/javascript\"></script-->\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body onScroll=\"document.cookie='ypos=' + window.pageYOffset\" onLoad=\"window.scrollTo(0,readCookie('ypos'))\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- pääsivun taustakuva -->\r\n");
      out.write("\t<div id=\"bg\">\r\n");
      out.write("\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t<header>\r\n");
      out.write("\t\t\t\t<!-- TODO: h1&p logot poistoon -->\r\n");
      out.write("\t\t\t\t<h1 class=\"logo hidden-xs\">\r\n");
      out.write("\t\t\t\t\tFIORI e<br> CASTELLO\r\n");
      out.write("\t\t\t\t</h1>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<p class=\"logo2 hidden-xs\">Restaurant & bar</p>\r\n");
      out.write("\t\t\t\t<p class=headerTxt>Lorem ipsum dolor sit amet. Lorem ipsum!</p>\r\n");
      out.write("\t\t\t\t<!-- TODO: YLEMPI TXTLOGO KORVATAAN ALEMMALLA KUVALOGOLLA-->\r\n");
      out.write("\t\t\t\t<!--img id=\"LOGO\" title=\"TITLE\" alt=\"logo\" src=\"img/logotähän.png\"></img-->\r\n");
      out.write("\t\t\t\t<!--div class=\"row\">\r\n");
      out.write("                    <div class=\"col-md-12 col-xs-12\" style=\"background:black;color:white\"></div>\r\n");
      out.write("                </div-->\r\n");
      out.write("\t\t\t\t<!--/div-->\r\n");
      out.write("\t\t\t\t<div class=\"row bottom\">\r\n");
      out.write("\t\t\t\t\t<p class=headerTxtSm>Tutustu meihin lisää</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</header>\r\n");
      out.write("\t\t<div id=\"customerBtnWrap\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t<div class=\"hidden-xs hidden-sm col-md-2 col-lg-2\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-6 col-md-4 col-lg-4\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"customerBtnContainer\">\r\n");
      out.write("\t\t\t\t\t\t<form action=\"TilausController\" method=\"get\">\r\n");
      out.write("\t\t\t\t\t\t\t<button id=\"onlineBtn\" class=\"customerBtn\" type=\"submit\" value=\"OnlineTilausnäkymä\" name=\"Submit\"\r\n");
      out.write("\t\t\t\t\t\t\tid=\"frm3_submit\"> <p>Tilaa noutopizzasi netistä</p> </button>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-6 col-md-4 col-lg-4\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"customerBtnContainer\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("<!-- Button trigger modal -->\r\n");
      out.write("<button id=\"varausBtn\" class=\"customerBtn\" data-toggle=\"modal\" data-target=\"#myModal\"><p>Tee pöytävaraus</p></button>\r\n");
      out.write("<!-- Modal -->\r\n");
      out.write("<div class=\"modal fade\" id=\"myModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("    <div class=\"vertical-alignment-helper\">\r\n");
      out.write("        <div class=\"modal-dialog vertical-align-center\">\r\n");
      out.write("            <div class=\"modal-content\">\r\n");
      out.write("                <div class=\"modal-header\">\r\n");
      out.write("                    <button type=\"button\" class=\"close\" data-dismiss=\"modal\"><span aria-hidden=\"true\">&times;</span><span class=\"sr-only\">Close</span>\r\n");
      out.write("\r\n");
      out.write("                    </button>\r\n");
      out.write("                     <h5 class=\"modal-title\" id=\"myModalLabel\">Pöytävaraukset</h5>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-body\">\r\n");
      out.write("                \t<div class=\"row\">\r\n");
      out.write("                \t\t<div class=\"col-md-12\">\r\n");
      out.write("                \t\t\t<p>Varaa ravintolastamme pöytä 2-6 hengen seurueelle.</p>\r\n");
      out.write("                \t\t\t<h4>Puh. +358 12312312</h4>\r\n");
      out.write("                \t\t</div>\r\n");
      out.write("                \t</div>\r\n");
      out.write("                \r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-footer\">\r\n");
      out.write("                    <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Palaa takaisin</button>\r\n");
      out.write("                    <!-- button type=\"button\" class=\"btn btn-primary\">Save changes</button-->\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- End Button trigger modal -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"hidden-xs hidden-sm hidden-md col-lg-2\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!--a href=\"#\" id=\"onlineBtn\" class=\"customerBtn\">\r\n");
      out.write("   \t\t\t\t <p>Tilaa noutopizzasi netistä</p>\r\n");
      out.write("   \t\t\t</a-->\r\n");
      out.write("   \t\t\t<!--a href=\"#\" id=\"varausBtn\" class=\"customerBtn\">\r\n");
      out.write("   \t\t\t\t <p>Tee pöytävaraus</p>\r\n");
      out.write("   \t\t\t</a-->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- navigointipalkki -->\r\n");
      out.write("\t<!--  todo: http://www.bootply.com/kD5wiG5udv-->\r\n");
      out.write("\t<div id=\"nav-wrap\">\r\n");
      out.write("\t\t<nav class=\"navbar navbar-default navbar-static-top shadow\" id=\"nav\"\r\n");
      out.write("\t\t\tdata-spy=\"affix\">\r\n");
      out.write("\t\t\t<!-- todo1: korjaa-->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Brand and toggle get grouped for better mobile display -->\r\n");
      out.write("\t\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t\t<button aria-expanded=\"false\" class=\"navbar-toggle collapsed\"\r\n");
      out.write("\t\t\t\t\tdata-target=\"#bs-example-navbar-collapse-1\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\t\t\ttype=\"button\">\r\n");
      out.write("\t\t\t\t\t<span class=\"sr-only\">Toggle navigation</span> <span\r\n");
      out.write("\t\t\t\t\t\tclass=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span\r\n");
      out.write("\t\t\t\t\t\tclass=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t<a class=\"navbar-brand visible-xs\" href=\"#\">Fiori e Castello</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- Collect the nav links, forms, and other content for toggling -->\r\n");
      out.write("\t\t\t<div class=\"collapse navbar-collapse\"\r\n");
      out.write("\t\t\t\tid=\"bs-example-navbar-collapse-1\">\r\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("\t\t\t\t\t<!--li class=\"active\"><a href=\"#\">LINKKI</a></li><span class=\"sr-only\">(aktiivinen)</span-->\r\n");
      out.write("\t\t\t\t\t<!-- aktiivinen linkki+screenreader class-->\r\n");
      out.write("\t\t\t\t\t<li><a class=\"page-scroll\" data-scroll-nav=\"0\" href=\"#info\">Tarinamme</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"page-scroll\" data-scroll-nav=\"1\" href=\"#ravintola\">Ravintola</a> <!-- kokit,puhtaus,tuoreus&laatu...--></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"page-scroll\" data-scroll-nav=\"2\" href=\"#ruoka\">Ruoka</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"page-scroll\" data-scroll-nav=\"3\" href=\"#sijainti\">Sijainti</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- /.navbar-collapse -->\r\n");
      out.write("\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t\t<!-- START PAGE 1, tietoa meistä -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"content-wrap content-bg\">\r\n");
      out.write("\t\t<!--  TODO: korvaa poistetut padding-top-## classit vakiotyyleillä contentwrappiin + TITLE -class pienellä, borders class pois ja integroi se otsikkoon(h2?) -->\r\n");
      out.write("\t\t<!--id=\"tietoa meistä\"-->\r\n");
      out.write("\t\t<div data-scroll-index=\"0\" class=\"container-fluid\" id=\"info\">\r\n");
      out.write("\t\t\t<!-- JS-scroll -viittaaja -->\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t<h2 class=\"subhead\">TARINAMME</h2>\r\n");
      out.write("\t\t\t\t\t<!-- todo: subhead == otsikon muotoilu -->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t<h3>FIORI e CASTELLO - LOREM IPSUM</h3>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-2 hidden-xs\"></div>\r\n");
      out.write("\t\t\t\t\t<!-- todo: testaa tyhjän col:n hidden toimivuus -->\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t\t\t\t\t<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.\r\n");
      out.write("\t\t\t\t\t\t\tSed posuere interdum sem. Quisque ligula eros ullamcorper quis,\r\n");
      out.write("\t\t\t\t\t\t\tlacinia quis facilisis sed sapien. Mauris varius diam vitae arcu.\r\n");
      out.write("\t\t\t\t\t\t\tLorem ipsum dolor sit amet, consectetuer adipiscing elit.</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t\t\t\t\t<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.\r\n");
      out.write("\t\t\t\t\t\t\tSed posuere interdum sem. Quisque ligula eros ullamcorper quis,\r\n");
      out.write("\t\t\t\t\t\t\tlacinia quis facilisis sed sapien. Mauris varius diam vitae arcu.</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-2 hidden-xs\"></div>\r\n");
      out.write("\t\t\t\t\t<!-- todo: testaa tyhjän col:n hidden toimivuus -->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- END PAGE 1 -->\r\n");
      out.write("\t<!-- DIVIDER BACKGROUND 1: BASIL -->\r\n");
      out.write("\t<section class=\"bg-1\" id=\"basil\"></section>\r\n");
      out.write("\t<!-- END DIVIDER BACKGROUND 1: BASIL -->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- START PAGE 2, ravintola info -->\r\n");
      out.write("\t<div class=\"content-wrap content-bg\">\r\n");
      out.write("\t\t<div data-scroll-index=\"1\" class=\"container-fluid\" id=\"ravintola\">\r\n");
      out.write("\t\t\t<!-- JS-scroll -viittaaja -->\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t<h2 class=\"subhead\">RAVINTOLA</h2>\r\n");
      out.write("\t\t\t\t\t<!-- todo: subhead == otsikon muotoilu -->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t<h3>FIORI e CASTELLO - HÄMEENLINNAN PIZZAMESTARIT</h3>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-2 hidden-xs\"></div>\r\n");
      out.write("\t\t\t\t\t<!-- todo: testaa tyhjän col:n hidden toimivuus -->\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t\t\t\t\t<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.\r\n");
      out.write("\t\t\t\t\t\t\tSed posuere interdum sem. Quisque ligula eros ullamcorper quis,\r\n");
      out.write("\t\t\t\t\t\t\tlacinia quis facilisis sed sapien. Mauris varius diam vitae arcu.\r\n");
      out.write("\t\t\t\t\t\t\tLorem ipsum dolor sit amet, consectetuer adipiscing elit.</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t\t\t\t\t<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.\r\n");
      out.write("\t\t\t\t\t\t\tSed posuere interdum sem. Quisque ligula eros ullamcorper quis,\r\n");
      out.write("\t\t\t\t\t\t\tlacinia quis facilisis sed sapien. Mauris varius diam vitae arcu.</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-2 hidden-xs\"></div>\r\n");
      out.write("\t\t\t\t\t<!-- todo: testaa tyhjän col:n hidden toimivuus -->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- END PAGE 2 -->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- DIVIDER BACKGROUND 2: MOZZARELLA -->\t\r\n");
      out.write("\t<section class=\"bg-2\" id=\"mozzarella\"></section>\r\n");
      out.write("\t<!-- END DIVIDER BACKGROUND 2: MOZZARELLA -->\t\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- START PAGE 3, ruoka+ruokalista -->\r\n");
      out.write("\t<div class=\"content-wrap content-bg\">\r\n");
      out.write("\t\t<div data-scroll-index=\"2\" class=\"container\" id=\"ruoka\" data-scroll-index=\"2\">\r\n");
      out.write("\t\t\t<!-- JS-scroll -viittaaja -->\r\n");
      out.write("\t\t\t<h2 class=\"subhead\">RUOKA</h2>\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-2 hidden-xs\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-8\">\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\tLorem ipsum dolor sit amet, consectetuer adipiscing elit. Sed\r\n");
      out.write("\t\t\t\t\t\t\tposuere interdum sem. Quisque ligula eros ullamcorper quis,\r\n");
      out.write("\t\t\t\t\t\t\tlacinia quis facilisis sed sapien. Mauris varius diam vitae arcu.<br>\r\n");
      out.write("\t\t\t\t\t\t\t<br> Lorem ipsum dolor sit amet, consectetuer adipiscing\r\n");
      out.write("\t\t\t\t\t\t\telit.\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<form action=\"TilausController\" method=\"get\">\r\n");
      out.write("\t\t\t\t\t\t\t<button id=\"onlineBtn\" class=\"customerBtn\" type=\"submit\" value=\"OnlineTilausnäkymä\" name=\"Submit\"\r\n");
      out.write("\t\t\t\t\t\t\tid=\"frm3_submit\"> <p>Tilaa noutopizzasi netistä</p> </button>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-2 hidden-xs\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--  start menu-accordion  -->\r\n");
      out.write("\t\t<div id=\"menuTop\" style=\"height: 63px;\"></div>\r\n");
      out.write("\t\t\t<!-- TODO: muut menun osiot kuntoon-->\r\n");
      out.write("\t\t\t<div aria-multiselectable=\"true\" class=\"panel-group\" id=\"accordion\"\r\n");
      out.write("\t\t\t\trole=\"tablist\">\r\n");
      out.write("\t\t\t\t<div class=\"panel panel-default\">\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-heading\" id=\"headingOne\" role=\"tab\">\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"panel-title accordionhead\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"menuTopBtn\" aria-controls=\"collapseOne\" aria-expanded=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-parent=\"#accordion\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"#collapseOne\" role=\"button\">Pizzat</a>\r\n");
      out.write("\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div aria-labelledby=\"headingOne\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"panel-collapse collapse\" id=\"collapseOne\"\r\n");
      out.write("\t\t\t\t\t\trole=\"tabpanel\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t\t\t\t<!--  \r\n");
      out.write("                            \r\n");
      out.write("                            <form action=\"ClientController\" method=\"get\">\r\n");
      out.write("                            \r\n");
      out.write("                            <button id=\"jarjestaHinta\" type=\"submit\" name=\"action\" value=\"jarjestaHinta\" onunload=\"unloadP('UniquePageNameHereScroll')\" onload=\"loadP('UniquePageNameHereScroll')\">Hintajärjestykseen</button>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" name=\"index\" value=\"jarjestaHinta\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<button id=\"jarjestaNimi\" type=\"submit\" name=\"action\" value=\"jarjestaNimi\">Aakkosjärjestykseen</button>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" name=\"index\" value=\"jarjestaNimi\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t-->\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<!-- toimivat napit, poistoon? \r\n");
      out.write("\t\t\t\t\t\t<form action=\"ClientController\" method=\"get\">\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"orderByBtn\" id=\"jarjestaHinta\" type=\"submit\" name=\"action\"\r\n");
      out.write("\t\t\t\t\t\t\t\tvalue=\"jarjestaHinta\">Hintajärjestykseen</button>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" name=\"index\" value=\"jarjestaHinta\" />\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"orderByBtn\" id=\"jarjestaNimi\" type=\"submit\" name=\"action\"\r\n");
      out.write("\t\t\t\t\t\t\t\tvalue=\"jarjestaNimi\">Aakkosjärjestykseen</button>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" name=\"index\" value=\"jarjestaNimi\" />\r\n");
      out.write("\t\t\t\t\t\t</form>-->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- div id=\"jarjestabox\"> <!-- oma testausbutton, ei toimi vielä -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<!-- div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"dropdown jarjestabox\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<form action=\"ClientController\" method=\"get\" class=\"jarjestabox\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button class=\"btn btn-default dropdown-toggle jarjestabox\" type=\"button\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tid=\"dropdownMenu1\" data-toggle=\"dropdown\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\taria-haspopup=\"true\" aria-expanded=\"true\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tHintajärjestykseen <span class=\"caret\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul class=\"dropdown-menu\" aria-labelledby=\"dropdownMenu1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a data-value=\"jarjestaHinta\">Hintajärjestykseen</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a data-value=\"jarjestaNimi\">Aakkosjärjestykseen</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div-->\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!--  div class=\"dropdown\">\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t<button class=\"btn btn-primary dropdown-toggle\" type=\"button\" data-toggle=\"dropdown\">Järjestys:\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t<span class=\"caret\"></span></button>\r\n");
      out.write("   \t\t\t\t\t\t \t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t\t<li><a href=\"#\" data-value=\"action\">Hintajärjestykseen</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\" data-value=\"another action\">Aakkosjärjestykseen</a></li>\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t</div-->\r\n");
      out.write("\r\n");
      out.write("<!--  desktopMenu -tulostus -->\t\t\t\r\n");
      out.write("<div id=\"desktopMenu\" class=\"hidden\">\t\t\t\t\t\t\t</div-->\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("<!--  TODO TODO: JAVAN SISÄLLÄ PUUTTUVIA/YLIMÄÄRÄISIÄ DIVEJÄ/DIVSULKUJA JOTKA RIKKOO SIVUN ACCORDIONIN JA DIVIDERIN(tomato) -->\r\n");
      out.write("\t\t\t\t\t\t\t");

								ArrayList<Pizza> pizzat = (ArrayList<Pizza>)request.getAttribute("pizzat");
							Locale locale  = new Locale("fi", "FI");
							String pattern = "##0.00";
							DecimalFormat desi = (DecimalFormat) NumberFormat.getNumberInstance(locale);
							desi.applyPattern(pattern);

	

																	                			
																	                      
							out.println("<div class=\"col-xs-6\">");
                      		 
                      		 for(int i=0; i < pizzat.size(); i+=2) {
               				out.print("<form action=\"Controller\" method=\"get\">");
               				
               				out.println("<div class=\"menuitembox\">");
               				
               				out.println("<tr>");
               				out.println("<td> <p class=\"lead menuitemhead\">" + pizzat.get(i).getNimi().toUpperCase() + " </p></td>");
               				out.println("<td> <p class=\"menufilling\">" + pizzat.get(i).getTaytteet() + " </p></td>");

               				out.println("<td> <p class=\"menuitemprice\">" + desi.format(pizzat.get(i).getHinta()) + "€</p></td>");			

               				out.println("</tr>");

               				out.println("</div>");
               				
           					out.println("<br>");
               				out.print("</form>");
               				out.println("<p class=\"lead dividerFlower\">❀</p>");
               			}
                      		
                      		out.println("</div>");
                      	
                      		
                     
                      		out.println("<div class=\"col-xs-6\">");
               			
               			for(int i=1; i < pizzat.size(); i+=2) {
               				out.print("<form action=\"Controller\" method=\"get\">");
               				out.println("<div class=\"menuitembox\">");
               					out.println("<tr>");
               					out.println("<td> <p class=\"lead menuitemhead\">" + pizzat.get(i).getNimi().toUpperCase() + " </p></td>");
               					out.println("<td> <p class=\"menufilling\">" + pizzat.get(i).getTaytteet() + " </p></td>");

               					out.println("<td> <p class=\"menuitemprice\">" + desi.format(pizzat.get(i).getHinta())+ "€</p></td>");
               					out.println("</tr>");
               				out.println("</div>");
               				
               				out.println("<br>");
               				out.print("</form>");
               				out.println("<p class=\"lead dividerFlower\">❀</p>");
               			}    
               			
               			out.println("</div>");
																	                		
																	                			

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- end menu -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"panel panel-default\">\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-heading\" id=\"headingTwo\" role=\"tab\">\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"panel-title accordionhead\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"menuTopBtn\" aria-controls=\"collapseTwo\" aria-expanded=\"false\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"collapsed\" data-parent=\"#accordion\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-toggle=\"collapse\" href=\"#collapseTwo\" role=\"button\">Virvoitusjuomat</a>\r\n");
      out.write("\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div aria-labelledby=\"headingTwo\" class=\"panel-collapse collapse\"\r\n");
      out.write("\t\t\t\t\t\tid=\"collapseTwo\" role=\"tabpanel\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"panel-body\">Anim pariatur cliche reprehenderit,\r\n");
      out.write("\t\t\t\t\t\t\tenim eiusmod high life accusamus terry richardson ad squid. 3\r\n");
      out.write("\t\t\t\t\t\t\twolf moon officia aute, non cupidatat skateboard dolor brunch.\r\n");
      out.write("\t\t\t\t\t\t\tFood truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon\r\n");
      out.write("\t\t\t\t\t\t\ttempor, sunt aliqua put a bird on it squid single-origin coffee\r\n");
      out.write("\t\t\t\t\t\t\tnulla assumenda shoreditch et. Nihil anim keffiyeh helvetica,\r\n");
      out.write("\t\t\t\t\t\t\tcraft beer labore wes anderson cred nesciunt sapiente ea\r\n");
      out.write("\t\t\t\t\t\t\tproident. Ad vegan excepteur butcher vice lomo. Leggings occaecat\r\n");
      out.write("\t\t\t\t\t\t\tcraft beer farm-to-table, raw denim aesthetic synth nesciunt you\r\n");
      out.write("\t\t\t\t\t\t\tprobably haven't heard of them accusamus labore sustainable VHS.\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"panel panel-default\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"panel-heading\" id=\"headingThree\" role=\"tab\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"panel-title accordionhead\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"menuTopBtn\" aria-controls=\"collapseThree\" aria-expanded=\"false\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"collapsed\" data-parent=\"#accordion\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-toggle=\"collapse\" href=\"#collapseThree\" role=\"button\">Viinit</a>\r\n");
      out.write("\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div aria-labelledby=\"headingThree\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"panel-collapse collapse\" id=\"collapseThree\"\r\n");
      out.write("\t\t\t\t\t\t\trole=\"tabpanel\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"panel-body\">Anim pariatur cliche reprehenderit,\r\n");
      out.write("\t\t\t\t\t\t\t\tenim eiusmod high life accusamus terry richardson ad squid. 3\r\n");
      out.write("\t\t\t\t\t\t\t\twolf moon officia aute, non cupidatat skateboard dolor brunch.\r\n");
      out.write("\t\t\t\t\t\t\t\tFood truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon\r\n");
      out.write("\t\t\t\t\t\t\t\ttempor, sunt aliqua put a bird on it squid single-origin coffee\r\n");
      out.write("\t\t\t\t\t\t\t\tnulla assumenda shoreditch et. Nihil anim keffiyeh helvetica,\r\n");
      out.write("\t\t\t\t\t\t\t\tcraft beer labore wes anderson cred nesciunt sapiente ea\r\n");
      out.write("\t\t\t\t\t\t\t\tproident. Ad vegan excepteur butcher vice lomo. Leggings\r\n");
      out.write("\t\t\t\t\t\t\t\toccaecat craft beer farm-to-table, raw denim aesthetic synth\r\n");
      out.write("\t\t\t\t\t\t\t\tnesciunt you probably haven't heard of them accusamus labore\r\n");
      out.write("\t\t\t\t\t\t\t\tsustainable VHS.</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"panel panel-default\">\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-heading\" id=\"headingFour\" role=\"tab\">\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"panel-title accordionhead\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"menuTopBtn\" aria-controls=\"collapseFour\" aria-expanded=\"false\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"collapsed\" data-parent=\"#accordion\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-toggle=\"collapse\" href=\"#collapseFour\" role=\"button\">Jälkiruoat</a>\r\n");
      out.write("\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div aria-labelledby=\"headingFour\" class=\"panel-collapse collapse\"\r\n");
      out.write("\t\t\t\t\t\tid=\"collapseFour\" role=\"tabpanel\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"panel-body\">Anim pariatur cliche reprehenderit,\r\n");
      out.write("\t\t\t\t\t\t\tenim eiusmod high life accusamus terry richardson ad squid. 3\r\n");
      out.write("\t\t\t\t\t\t\twolf moon officia aute, non cupidatat skateboard dolor brunch.\r\n");
      out.write("\t\t\t\t\t\t\tFood truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon\r\n");
      out.write("\t\t\t\t\t\t\ttempor, sunt aliqua put a bird on it squid single-origin coffee\r\n");
      out.write("\t\t\t\t\t\t\tnulla assumenda shoreditch et. Nihil anim keffiyeh helvetica,\r\n");
      out.write("\t\t\t\t\t\t\tcraft beer labore wes anderson cred nesciunt sapiente ea\r\n");
      out.write("\t\t\t\t\t\t\tproident. Ad vegan excepteur butcher vice lomo. Leggings occaecat\r\n");
      out.write("\t\t\t\t\t\t\tcraft beer farm-to-table, raw denim aesthetic synth nesciunt you\r\n");
      out.write("\t\t\t\t\t\t\tprobably haven't heard of them accusamus labore sustainable VHS.\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t<!-- end menu-accordion -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- acc end testing comment (remove) -->\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- ENG PAGE 3 -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t<!-- DIVIDER BACKGROUND 3: TOMATO -->\t\r\n");
      out.write("\t<section class=\"bg-3\" id=\"tomato\"></section>\r\n");
      out.write("\t<!-- END DIVIDER BACKGROUND 3: TOMATO -->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- START PAGE 4, sijainti/location -->\r\n");
      out.write("\t<div class=\"content-wrap content-bg lastbg\">\r\n");
      out.write("\t\t<div data-scroll-index=\"3\" class=\"container-fluid\" id=\"sijainti\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t<h2 class=\"subhead\">YHTEYSTIEDOT</h2>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t<h4>Ravintolamme sijaitsee aivan Hämeenlinnan keskustassa</h4>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t<p class=\"br\"> Hämeenlinnankatu 2</p>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("<!-- google map -->\r\n");
      out.write("<script src=\"https://maps.googleapis.com/maps/api/js?sensor=false\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"js/googlemap.js\"></script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("/* Set a size for our map container, the Google Map will take up 100% of this container */\r\n");
      out.write("#map {\r\n");
      out.write("\twidth: 70%;\r\n");
      out.write("\theight: 360px;\r\n");
      out.write("\tmargin: 0 auto;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\t\t\t\t\t<div id=\"map\"></div>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- FOOTER -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- TODO: muokkaa uudenlainen, copyright ihan alas, collapsekäyttäytyminen uusiks napeille(md vs xs)-->\r\n");
      out.write("\t\t<div id=\"footer\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-2\"></div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"underline\">YHTEYSTIEDOT</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"inner\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4>KÄYNTIOSOITE:</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"br\"> Hämeenlinnankatu 2</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4>PUHELIN:</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"br\">+358 12312312</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4>SÄHKÖPOSTI:</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"br\">info@fioriecastello.fi</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"underline\"> AUKIOLOAJAT </h4>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"inner\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4>MA-PE:</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"br\">9-23</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4>LAUANTAI:</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"br\">11-23</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4>SUNNUNTAI:</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"br\">11-21</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-2\"></div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"footerBottom container\">\t\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-4>\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"underline\">SEURAA MEITÄ</h4>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-12 inner\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-3\"></div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-2\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"fa fa-facebook fa-3x\"></i>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-2\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"fa fa-pinterest-p fa-3x\"></i>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-2\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"fa fa-instagram fa-3x\"></i>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-3\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- END PAGE 4 -->\r\n");
      out.write("\t\r\n");
      out.write("\t<ul class=\"nav pull-right scroll-top hidden\">\r\n");
      out.write("  \t\t<li><a href=\"#\" title=\"Takaisin alkuun\"><i class=\"glyphicon glyphicon-chevron-up\"></i></a></li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- SCRIPT INCLUDE -->\r\n");
      out.write("\t<script src=\"js/jquery-2.1.4.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/scrollit.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/jquery.easing.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/scrolling-nav.js\"></script>\r\n");
      out.write("\t<!-- END SCRIPT INCLUDE -->\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\r\n");
      out.write("    /* affix the navbar after scroll below header\r\n");
      out.write("$('#nav').affix({\r\n");
      out.write("      offset: {\r\n");
      out.write("        top: $('header').height()-$('#nav').height()\r\n");
      out.write("      }\r\n");
      out.write("});\t\r\n");
      out.write(" */\r\n");
      out.write(" /*hinta/aakkosjärjestysnappi\r\n");
      out.write(" $(\".dropdown-menu li a\").click(function(){\r\n");
      out.write("\t  $(this).parents(\".dropdown\").find('.btn').html($(this).text() + ' <span class=\"caret\"></span>');\r\n");
      out.write("\t  $(this).parents(\".dropdown\").find('.btn').val($(this).data('value'));\r\n");
      out.write("\t});\r\n");
      out.write(" */\r\n");
      out.write(" /*accordion ruokalista-kohdistus*/ \r\n");
      out.write(" $(\".menuTopBtn\").click(function() {\r\n");
      out.write("     $('html, body').animate({\r\n");
      out.write("         scrollTop: $(\"#MenuTop\").offset().top\r\n");
      out.write("     }, 2000);\r\n");
      out.write(" });\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write(" /*navbar script /w width detect */\r\n");
      out.write(" jQuery(document).ready(function(){\r\n");
      out.write("\r\n");
      out.write("\t\tvar width2 = jQuery(window).width();\r\n");
      out.write("\r\n");
      out.write("\t\tif(width2 > 768)\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(function(){\r\n");
      out.write("\t\t\t    $('#nav-wrap').height($(\".navbar\").height());\r\n");
      out.write("\r\n");
      out.write("\t\t\t    $('.navbar').affix({\r\n");
      out.write("\t\t\t        offset: { top: $('.navbar').offset().top }\r\n");
      out.write("\t\t\t    });\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t});\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("/*navbar script\r\n");
      out.write("$(function(){\r\n");
      out.write("    $('#nav-wrap').height($(\".navbar\").height());\r\n");
      out.write("\r\n");
      out.write("    $('.navbar').affix({\r\n");
      out.write("        offset: { top: $('.navbar').offset().top }\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("*/\r\n");
      out.write("\r\n");
      out.write("/*scroll to top*/\r\n");
      out.write("$(document).scroll(function () {\r\n");
      out.write("    var y = $(this).scrollTop();\r\n");
      out.write("    if (y > 60) {\r\n");
      out.write("    \t$('.scroll-top').removeClass( \"hidden\" );\r\n");
      out.write("     \t$('.scroll-top').addClass( \"visible\" );\r\n");
      out.write("    } else {\r\n");
      out.write("    \t$('.scroll-top').removeClass( \"visible\" );\r\n");
      out.write("        $('.scroll-top').addClass( \"hidden\" );\r\n");
      out.write("    }\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$('.scroll-top').click(function(){\r\n");
      out.write("    $(\"html, body\").animate({ scrollTop: 0 }, 800);\r\n");
      out.write("    return false;\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("/**\r\n");
      out.write(" * Author: Heather Corey\r\n");
      out.write(" * jQuery Simple Parallax Plugin\r\n");
      out.write(" *\r\n");
      out.write(" */\r\n");
      out.write(" \r\n");
      out.write("(function($) {\r\n");
      out.write(" \r\n");
      out.write("    $.fn.parallax = function(options) {\r\n");
      out.write(" \r\n");
      out.write("        var windowHeight = $(window).height();\r\n");
      out.write(" \r\n");
      out.write("        // Establish default settings\r\n");
      out.write("        var settings = $.extend({\r\n");
      out.write("            speed        : 0.15\r\n");
      out.write("        }, options);\r\n");
      out.write(" \r\n");
      out.write("        // Iterate over each object in collection\r\n");
      out.write("        return this.each( function() {\r\n");
      out.write(" \r\n");
      out.write("        \t// Save a reference to the element\r\n");
      out.write("        \tvar $this = $(this);\r\n");
      out.write(" \r\n");
      out.write("        \t// Set up Scroll Handler\r\n");
      out.write("        \t$(document).scroll(function(){\r\n");
      out.write(" \r\n");
      out.write("    \t\t        var scrollTop = $(window).scrollTop();\r\n");
      out.write("            \t        var offset = $this.offset().top;\r\n");
      out.write("            \t        var height = $this.outerHeight();\r\n");
      out.write(" \r\n");
      out.write("    \t\t// Check if above or below viewport\r\n");
      out.write("\t\t\tif (offset + height <= scrollTop || offset >= scrollTop + windowHeight) {\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write(" \r\n");
      out.write("\t\t\tvar yBgPosition = Math.round((offset - scrollTop) * settings.speed);\r\n");
      out.write(" \r\n");
      out.write("                 // Apply the Y Background Position to Set the Parallax Effect\r\n");
      out.write("    \t\t\t$this.css('background-position', 'center ' + yBgPosition + 'px');\r\n");
      out.write("                \r\n");
      out.write("        \t});\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("}(jQuery));\r\n");
      out.write("\r\n");
      out.write("$('.bg-1,.bg-3').parallax({\r\n");
      out.write("\tspeed :\t0.25\r\n");
      out.write("});\t\r\n");
      out.write("\t\r\n");
      out.write("$('.bg-2').parallax({\r\n");
      out.write("\tspeed :\t0.35\r\n");
      out.write("});\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("/* detect mobile/desktop resolution & switch menutypes accordingly */\t\r\n");
      out.write("jQuery(document).ready(function(){\r\n");
      out.write("\r\n");
      out.write("\tvar width = jQuery(window).width();\r\n");
      out.write("\r\n");
      out.write("\tif(width < 480)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tjQuery('#desktopMenu').removeClass('visible');\r\n");
      out.write("\t\tjQuery('#desktopMenu').addClass('hidden');\r\n");
      out.write("\t\tjQuery('#mobileMenu').removeClass('hidden');\r\n");
      out.write("\t\tjQuery('#mobileMenu').addClass('visible');\r\n");
      out.write("\t}\r\n");
      out.write("\telse\r\n");
      out.write("\t{\r\n");
      out.write("\t\tjQuery('#desktopMenu').removeClass('hidden');\r\n");
      out.write("\t\tjQuery('#desktopMenu').addClass('visible');\r\n");
      out.write("\t\tjQuery('#mobileMenu').removeClass('visible');\r\n");
      out.write("\t\tjQuery('#mobileMenu').addClass('hidden');\r\n");
      out.write("\t}\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* highlight the top nav as scrolling occurs \r\n");
      out.write("$('body').scrollspy({ target: '#nav' })\r\n");
      out.write("*/\r\n");
      out.write("/* smooth scrolling for scroll to top\r\n");
      out.write("$('.scroll-top').click(function(){\r\n");
      out.write("  $('body,html').animate({scrollTop:0},1000);\r\n");
      out.write("})\r\n");
      out.write(" */\r\n");
      out.write(" \r\n");
      out.write("/* smooth scrolling for nav sections \r\n");
      out.write("$('#nav .navbar-nav li>a').click(function(){\r\n");
      out.write("  var link = $(this).attr('href');\r\n");
      out.write("  var posi = $(link).offset().top;\r\n");
      out.write("  $('body,html').animate({scrollTop:posi},700);\r\n");
      out.write("});\r\n");
      out.write("*/\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("  /*   \r\n");
      out.write("            $(function(){\r\n");
      out.write("    $('#nav-wrap').height($(\".navbar\").height());\r\n");
      out.write("\r\n");
      out.write("    $('.navbar').affix({\r\n");
      out.write("        offset: { \r\n");
      out.write("\t\ttop:  $('.navbar').offset().top \r\n");
      out.write("\t\t}\r\n");
      out.write("    });\r\n");
      out.write("    });\r\n");
      out.write("*/\r\n");
      out.write("/*\r\n");
      out.write("    $(function(){\r\n");
      out.write("    $.scrollIt();\r\n");
      out.write("    });\r\n");
      out.write("\t*/\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("/*<!-- bs-kuvacarousel -->\r\n");
      out.write("            <div class=\"carousel slide\" data-ride=\"carousel\" id=\"myCarousel\">\r\n");
      out.write("                <!-- Indicators -->\r\n");
      out.write("                <ol class=\"carousel-indicators\">\r\n");
      out.write("                    <li class=\"active\" data-slide-to=\"0\" data-target=\r\n");
      out.write("                    \"#myCarousel\"></li>\r\n");
      out.write("                    <li data-slide-to=\"1\" data-target=\"#myCarousel\"></li>\r\n");
      out.write("                    <li data-slide-to=\"2\" data-target=\"#myCarousel\"></li>\r\n");
      out.write("                    <li data-slide-to=\"3\" data-target=\"#myCarousel\"></li>\r\n");
      out.write("                </ol><!-- Wrapper for slides --><!-- TODO: poista(?) html stylet -->\r\n");
      out.write("                <div class=\"carousel-inner\" role=\"listbox\"><!--TODO: muuta style=\"height: 100%;\"-->\r\n");
      out.write("                    <div class=\"item active\"><img alt=\"PIZZA\" class=\"slide\"\r\n");
      out.write("                    src=\"img/1x.jpg\" style=\"height: 55em;\"></div>\r\n");
      out.write("                    <div class=\"item\"><img alt=\"PIZZA\" class=\"slide\" src=\r\n");
      out.write("                    \"img/2x.jpg\" style=\"height: 55em;\"></div>\r\n");
      out.write("                    <div class=\"item\"><img alt=\"PIZZA\" class=\"slide\" src=\r\n");
      out.write("                    \"img/3x.jpg\" style=\"height: 55em;\"></div>\r\n");
      out.write("                    <div class=\"item\"><img alt=\"PIZZA\" class=\"slide\" src=\r\n");
      out.write("                    \"img/4x.jpg\" style=\"height: 55em;\"></div>\r\n");
      out.write("                </div><!-- Left and right controls -->\r\n");
      out.write("                <a class=\"left carousel-control\" data-slide=\"prev\" href=\r\n");
      out.write("                \"#myCarousel\" role=\"button\"><span aria-hidden=\"true\" class=\r\n");
      out.write("                \"glyphicon glyphicon-chevron-left\"></span> <span class=\r\n");
      out.write("                \"sr-only\">Edellinen</span></a> <a class=\r\n");
      out.write("                \"right carousel-control\" data-slide=\"next\" href=\"#myCarousel\"\r\n");
      out.write("                role=\"button\"><span aria-hidden=\"true\" class=\r\n");
      out.write("                \"glyphicon glyphicon-chevron-right\"></span> <span class=\r\n");
      out.write("                \"sr-only\">Seuraava</span></a>\r\n");
      out.write("            </div>*/\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
