/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2016-02-25 18:51:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Locale;
import java.text.NumberFormat;
import java.text.DecimalFormat;
import java.util.ArrayList;
import fi.pizzeriaprojekti.admin.bean.*;

public final class onlineTilaus_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/Tyotilat/Pizzeria/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/PizzeriaProjekti/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153374282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1456425564713L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("fi.pizzeriaprojekti.admin.bean");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Locale");
    _jspx_imports_classes.add("java.text.DecimalFormat");
    _jspx_imports_classes.add("java.text.NumberFormat");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta content=\"IE=edge\" http-equiv=\"X-UA-Compatible\">\r\n");
      out.write("<meta content=\"width=device-width, initial-scale=1\" name=\"viewport\">\r\n");
      out.write("<title>Ravintola - FIORI e CASTELLO - Onlinetilaus</title>\r\n");
      out.write("<link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"css/tyyli.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<link href='https://fonts.googleapis.com/css?family=Josefin+Sans:600'\r\n");
      out.write("\trel='stylesheet' type='text/css'>\r\n");
      out.write("<link href='https://fonts.googleapis.com/css?family=Hammersmith+One'\r\n");
      out.write("\trel='stylesheet' type='text/css'>\r\n");
      out.write("<link href='https://fonts.googleapis.com/css?family=Capriola'\r\n");
      out.write("\trel='stylesheet' type='text/css'>\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function readCookie(name){\r\n");
      out.write("return(document.cookie.match('(^|; )'+name+'=([^;]*)')||0)[2]\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//takaisin etusivulle alert\t\r\n");
      out.write("function pois() {\r\n");
      out.write("\t\r\n");
      out.write("\tvar go = \"http://proto293:8080/PizzeriaProjekti/ClientController\";\r\n");
      out.write("\t \r\n");
      out.write("\r\n");
      out.write("\tanswer = confirm(\"Olet poistumassa OnlineTilauksesta. Oletko varma?\")\r\n");
      out.write("\r\n");
      out.write("\tif (answer !=0){\r\n");
      out.write("\t\twindow.location = go; \r\n");
      out.write("\t} \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body onScroll=\"document.cookie='ypos=' + window.pageYOffset\" onLoad=\"window.scrollTo(0,readCookie('ypos'))\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t");

	Locale locale  = new Locale("fi", "FI");
	String pattern = "##0.00";
	DecimalFormat desi = (DecimalFormat) NumberFormat.getNumberInstance(locale);
	desi.applyPattern(pattern);
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!--navbar beginning----------------------------------------------------------------------------->\r\n");
      out.write("\r\n");
      out.write("\t<nav class=\"navbar navbar-default navbar-fixed-top\">\r\n");
      out.write("\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t<button type=\"button\" class=\"navbar-toggle collapsed\"\r\n");
      out.write("\t\t\t\tdata-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\">\r\n");
      out.write("\t\t\t\t<span class=\"sr-only\">Toggle navigation</span> <span\r\n");
      out.write("\t\t\t\t\tclass=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span\r\n");
      out.write("\t\t\t\t\tclass=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<a class=\"navbar-brand\" id=\"poispois\" href=\"http://localhost:8080/PizzeriaProjekti/ClientController\" onClick=\"pois();return false;\">Takaisin etusivulle</a>\r\n");
      out.write("\r\n");
      out.write("\t\t</div> \r\n");
      out.write("<!-- -----------------------------------------------------ostoskori beginning----------------------- -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");

							if(session != null && session.getAttribute("kori")!=null ) {
										            	ArrayList<ostoskoriPizza> ostoskoriPizzat = (ArrayList<ostoskoriPizza>)session.getAttribute("kori");
										            	
										            	
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"collapse navbar-collapse\"\r\n");
      out.write("\t\t\tid=\"bs-example-navbar-collapse-1\">\r\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("\t\t\t\t<li class=\"dropdown\" id=\"ostosKori\"><a href=\"#\" class=\"dropdown-toggle\"\r\n");
      out.write("\t\t\t\t\tdata-toggle=\"dropdown\" role=\"button\" aria-expanded=\"false\"> <span\r\n");
      out.write("\t\t\t\t\t\tclass=\"glyphicon glyphicon-shopping-cart\"></span>Tuotteet<span\r\n");
      out.write("\t\t\t\t\t\tclass=\"caret\"></span></a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"dropdown-menu dropdown-cart\" role=\"menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t            \t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t            \t");
		            	
										            	for(int i=0; i< ostoskoriPizzat.size(); i++) {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<li><span class=\"item\"> <span class=\"item-left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"img/minipizza.png\" alt=\"\" /> <span class=\"item-info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span>");
      out.print(ostoskoriPizzat.get(i).getNimi());
      out.write("</span> <span>");
      out.print(desi.format(ostoskoriPizzat.get(i).getHinta()));
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span>");
      out.print(ostoskoriPizzat.get(i).getLkm() );
      out.write("</span></span>\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<form action=\"TilausController\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"item-right\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"hidden\" class=\"btn btn-xs btn-danger pull-right\" name=\"action\" value=\"poistakorista\" /> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"pizzanumero\" value=\"");
out.print(ostoskoriPizzat.get(i).getId()); 
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button class=\"btn btn-xs btn-danger pull-right\" type=\"submit\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tx\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</button></span>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t");

							}
										            }
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");

							if(session != null && session.getAttribute("kori")!=null ) {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<form action=\"TilausController\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"action2\" method=\"post\" value=\"tyhjaa\"/>\r\n");
      out.write("\t\t\t\t\t\t<button type=\"submit\" class=\"text-center\">Tyhjää kori</button>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t<li><a class=\"text-center\" href=\"kassaNakyma.jsp\">Siirry kassalle</a></li>\r\n");
      out.write("\t\t\t\t\t\t");

							}
						
      out.write("\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- beginning of header------------------------------------------------------------------------------------>\r\n");
      out.write("<header>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"header\" class=\"shadow\">\r\n");
      out.write("\t\t<!-- Logo -->\r\n");
      out.write("\t\t<div class=\"hidden-xs col-sm-4 col-md-4 col-lg-4\">\r\n");
      out.write("\t\t\t<img alt=\"logo\" id=\"logo\" src=\"img/logo_yellow_sm.png\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Teksti -->\r\n");
      out.write("\t\t<div class=\"col-xs-12 col-sm-8 col-md-8 col-lg-6\">\r\n");
      out.write("\t\t\t<div class=\"intro\">\r\n");
      out.write("\t\t\t\t<h1 class=\"h1Head\">Tervetuloa onlinetilaukseen!</h1>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t***Huom! Vain nouto!***<br> Voitte nauttia pizzoista myös\r\n");
      out.write("\t\t\t\t\txxxxkadun ravintolassamme. Pöytävarauksen voit tehdä soittamalla\r\n");
      out.write("\t\t\t\t\tnumeroon 123456789.\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<h1 class=\"h1Head\">Aukioloajat</h1>\r\n");
      out.write("\t\t\t\tMA-PE 10:30 - 21:00 <br>LAUANTAI 11:30 - 21:00 <br>SUNNUNTAI\r\n");
      out.write("\t\t\t\t11:30 - 18:00\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-md-2 col-lg-2 hidden-xs hidden-sm\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"rako\">\r\n");
      out.write("\t<form action=\"TilausController\" method=\"get\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<select name='action' onchange='this.form.submit()' class=\"jarjesta\">\r\n");
      out.write("\t\t\t\t<option>Järjestä</option>\r\n");
      out.write("\t\t\t\t<option value=\"jarjestaHinta\"><a href=\"http://localhost:8080/PizzeriaProjekti/TilausController?action=jarjestaHinta&index=jarjestaHinta&index=jarjestaNimi\">Hintajärjestykseen</a></option>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<option value=\"jarjestaNimi\"><a href=\"http://localhost:8080/PizzeriaProjekti/TilausController?index=jarjestaHinta&action=jarjestaNimi&index=jarjestaNimi\">Aakkosjärjestykseen</a></option>\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t\t<noscript>\r\n");
      out.write("\t\t\t\t<input type=\"submit\" value=\"Submit\">\r\n");
      out.write("\t\t\t</noscript>\r\n");
      out.write("\r\n");
      out.write("\t\t</form>\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t<!----------------------------------------------------------------end of header--------------------------------->\r\n");
      out.write("\r\n");
      out.write("\t<!----------------------------------------------------beginning of pizzas------------------------------------->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- PIZZA CONTAINER  -->\t\t\t\t\t\t\t                \t\t\t\t\r\n");
      out.write("<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t");

				ArrayList<Pizza> pizzat = (ArrayList<Pizza>)request.getAttribute("pizzat");

						
				for(int i=0; i < pizzat.size(); i++) {
				out.print("<form action=\"TilausController\" method=\"get\">");
						

						/*PIZZA COL*/
						out.println("<div class=\"col-xs-12 col-sm-6 col-md-6 col-lg-4\">");
						
						/*PIZZA CONTAINER*/
						out.println("<div class=\"pizzaContainer\">");
						
							/*PHOTOBOX*/
							out.println("<div class=\"col-xs-12 boxPizzaImg\">");		
								out.println("<img class=\"pizzaPhoto\"alt=\"photo of pizza\" id=\"pizza1\" src=\"img/pizza-b2.png\" >");
							out.println("</div>");
							/*END PHOTOBOX*/
							
							/*TEXTBOX*/
							out.println("<div class=\"col-xs-12 boxPizzaTxt\">");
								/*TEXT*/ 
								out.println("<div class=\"menuitemheadBox\">");
								out.println("<p class=\"lead menuitemhead\">" + pizzat.get(i).getNimi().toUpperCase() + " </p>");
								out.println("</div>");
								out.println("<p class=\"menufilling\">" + pizzat.get(i).getTaytteet() + " </p>");
								
								out.println("<div class=\"row price\">");
									out.println("<div class=\"col-xs-12 center noMarginPadding\">");
										out.println("<h5 class=\"menuitemprice\">" + desi.format(pizzat.get(i).getHinta()) + "€</h5>");
									out.println("</div>");
								out.println("</div>");
								
								/*BUTTON ROW*/	
								out.println("<div class=\"row bottom\">");
									out.println("<div class=\"col-xs-12 center noMarginPadding\">");
									
									/*LKM TXT*/
									out.println("<div class=\"col-xs-5 \">");
										out.println("<p>Lukumäärä:</p>");

									out.println("</div>");
									
									
out.print("</form>");
									
									out.print("<form action=\"TilausController\" method=\"post\">");
									/*LKM*/
									out.println("<div class=\"col-xs-2  center noMarginPadding\">");
									
									out.println("<input class=\"inputSmall\" type=\"number\" size=\"2\" name=\"lkm\" min=\"1\" max=\"25\" value= \"1\">");
									out.println("</div>");
									
									/*BUTTON*/
									out.println("<div class=\"col-xs-5 center noMarginPadding\">");
									
									
									
										out.println("<input type=\"hidden\" name=\"action\" value=\"lisaa\"/>");
										out.println("<input type=\"hidden\" name=\"pizzanumero\" value=\""+pizzat.get(i).getId()+"\"/>");
									
										out.println("<button class=\"btn btn-primary btn-sm outline lisaanappi\" type=\"submit\"><b>Lisää koriin</b></button>");
									out.println("</div>");
									
										
									out.println("</div>");
								/*END CHECKBOX/BUTTON ROW*/	
								out.println("</div>");
							/*END TEXTBOX*/	
							out.println("</div>");
							
						/*END PIZZA CONTAINER*/
						out.println("</div>");	
						
						/*END PIZZA COL*/
						out.println("</div>");
					
						
					
				out.print("</form>");
				}		
						
		
			
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- END PIZZA CONTAINER  -->\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!--end of pizzas----------------------------------------------------------------------------------->\r\n");
      out.write("\t<div class=\"rako\"></div>\r\n");
      out.write("\t<!--beginning of footer----------------------------------------------------------------------------->\r\n");
      out.write("\t<div id=\"footer\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t<p>something something</p>\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<p>FIORI e CASTELLO 2015</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-2\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-facebook fa-3x\"></i>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-2\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-pinterest-p fa-3x\"></i>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-2\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-instagram fa-3x\"></i>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--end of footer--------------------------------------------------------------------------------->\r\n");
      out.write("\t<!--scrollup-------------------------------------------------------------------------------------->\r\n");
      out.write("\t<ul class=\"nav pull-right scroll-top hidden\">\r\n");
      out.write("  \t\t<li><a href=\"#\" title=\"Takaisin alkuun\"><i class=\"glyphicon glyphicon-chevron-up\"></i></a></li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("\t<!--/scrollup------------------------------------------------------------------------------------->\r\n");
      out.write("\t<script src=\"js/jquery-2.1.4.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"js/index.js\" type=\"text/javascript\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
